services:
  java-app:
    image: maven:3.8.3-openjdk-17
    container_name: java-app
    working_dir: /app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DB}?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./../src:/app/src
      - ./../pom.xml:/app/pom.xml
      - ./../logs:/app/logs
      - maven_repo:/root/.m2
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - db

  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  maven_repo:
